version: "2.2"

services:
  backend:
    image: node:alpine
    container_name: backend
    entrypoint: "npm start --prefix /src"
    environment:
      - PORT=5000
      - ADMIN_USER_NAME=admin
      - ADMIN_USER_PASSWORD=123
      - SMTP_HOST=smtp.mail.ru
      - SMTP_PORT=2525
      - SMTP_USER_NAME=otus.test@mail.ru
      - SMTP_USER_PASSWORD=rdtsc0f31
      - PUSH_PUBLIC_KEY=BEaS-dIxzeEOAebAizEmzxIsZmJ4NDuUFexpauuWZn7MiVOHn1wYwB4FoC_TmxilOVM3oRrUBWgkZ2pSbOLjDYw
      - PUSH_PRIVATE_KEY=RpyWiKqRR5Etm29UxvqOg-P-lswiWv_Qoy6Yv2DQ3J0
    volumes:
      - ./backend:/src
    ports:
      - 5000:5000

  frontend:
    image: node:alpine
    container_name: frontend
    entrypoint: "npm start --prefix /src"
    volumes:
      - ./frontend:/src
    ports:
      - 3000:3000

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger.api.yml
    ports:
      - 5001:8080
    volumes:
      - ./backend/swagger.api.yml:/swagger.api.yml
