swagger: "2.0"
info:
  title: Bitcoin lottery API
  version: "2.0"
host: localhost:5000
basePath: /
schemes:
  - http
paths:
  /bet:
    get:
      tags:
        - debug
        - auth cookie
        - bet
      summary: Retruns a list of bets.
      responses:
        '200':
         description: OK
    post:
      tags:
        - bet
        - auth cookie
      summary: Makes a new bet.
      responses:
        '200':
          description: OK
  /auth:
    get:
      tags:
        - debug
        - user
      summary: Returns an array of sessions.
      responses:
        '200':
          description: OK
    post:
      tags:
        - auth cookie
        - user
      summary: Authenticates user by username and password. Retruns sessionId.
      consumes:
        - application/x-www-form-urlencoded
      responses:
        '200':
          description: OK
      parameters:
        - in: formData
          name: user
          type: string
          description: Name of user
        - in: formData
          name: pass
          type: string
          description: Password
  /random01:
    get:
      tags:
        - bet
      summary: Returns 0 or 1.
      responses:
        '200':
         description: OK
  /user:
    get:
      tags:
        - user
        - debug
      summary: Returns a list of users.
      responses:
        '200':
          description: OK
    post:
      tags:
        - user
      summary: Creates a new user.
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: user
          type: string
          description: Name of user
        - in: formData
          name: pass
          type: string
          description: Password
        - in: formData
          name: email
          type: string
          description: E-mail
      responses:
        '200':
          description: OK
  /wallet:
    get:
      tags:
        - user
        - debug
      summary: Returns a list of wallets.
      responses:
        '200':
          description: OK
    post:
      tags:
        - user
        - auth cookie
      summary: Creates a new wallet.
      consumes:
        - application/x-www-form-urlencoded
      responses:
        '200':
          description: OK
      parameters:
        - in: formData
          name: userId
          type: string
          description: User unique identificator
  /notification:
    post:
      tags:
        - notification
      summary: Sends push notification and email.
      parameters:
        - in: formData
          name: to
          type: string
          description: Recipient email address.
        - in: formData
          name: title
          type: string
          description: Title of the notification.
        - in: formData
          name: message
          type: string
          description: Message of the notification.
      responses:
        '200':
          description: OK
  /mail:
    post:
      tags:
        - notification
      summary: Sends e-mail notification.
      responses:
        '200':
          description: OK
      parameters:
        - in: formData
          name: to
          type: string
          description: Recipient email address.
        - in: formData
          name: subject
          type: string
          description: Subject of the e-mail message.
        - in: formData
          name: message
          type: string
          description: Text of the e-mail message.
  /push:
    get:
      tags:
        - debug
        - notification
      summary: Shows subscription endpoint.
      responses:
        '200':
          description: OK
  /push/public/key:
    get:
      tags:
        - debug
        - notification
      summary: Shows public key for subscription endpoint.
      responses:
        '200':
          description: OK
  /push/send:
    post:
      tags:
        - notification
      summary: Sends push notifications to the client browser.
      parameters:
        - in: formData
          name: title
          type: string
          description: Title of the notification.
        - in: formData
          name: message
          type: string
          description: Message of the notification.
      responses:
        '200':
          description: OK
  /push/save:
    post:
      tags:
        - notification
      summary: Saves push notifications.
      requestBody:
        content:
          text/html:
            schema:
              type: string
      responses:
        '200':
          description: OK